In [1]:
import numpy as np
import time
import os
os.chdir('/home/koritskiy/Yandex.Disk/personal/rqc/markowitz_partitioning')
os.getcwd()
from modules.partitioning import Partitioning

In [16]:
import itertools
block_dims = []
for length in range(3, 7):
    for dims in itertools.combinations_with_replacement([3,4,5,6], length):
        block_dims.append(list(dims))
print(len(block_dims))

195


In [30]:
for block_dim in block_dims:
    block_dim_name = ''.join([str(i) for i in block_dim])
    block_mat = Partitioning.rand_sym_block_gen(block_dim, order = True)
    (_, mixed_mat, mix_permutation_mat) = Partitioning.mixed_matrix_generator(block_mat=block_mat)
    path = "/home/koritskiy/Yandex.Disk/personal/rqc/markowitz_partitioning/data/test_matrices/" + str(block_dim_name)
    if not os.path.exists(path):
        os.makedirs(path)
    np.savetxt(path + "/block_mat" + str(block_dim_name) + ".csv", block_mat, delimiter=",")
    np.savetxt(path + "/mixed_mat" + str(block_dim_name) + ".csv", mixed_mat, delimiter=",")
    np.savetxt(path + "/mix_permutation_mat" + str(block_dim_name) + ".csv", mix_permutation_mat, delimiter=",")

Given random block matrix:
[[0.9208472  0.61705494 0.37616856 0.         0.         0.
  0.         0.         0.        ]
 [0.61705494 0.96154184 0.62267533 0.         0.         0.
  0.         0.         0.        ]
 [0.37616856 0.62267533 0.80991742 0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.83439904 0.74093698 0.49653289
  0.         0.         0.        ]
 [0.         0.         0.         0.74093698 0.89424373 0.67666195
  0.         0.         0.        ]
 [0.         0.         0.         0.49653289 0.67666195 0.88256008
  0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.95828384 0.65607929 0.38544873]
 [0.         0.         0.         0.         0.         0.
  0.65607929 0.83423747 0.71274924]
 [0.         0.         0.         0.         0.         0.
  0.38544873 0.71274924 0.90499496]]


Random permutation matrix:
[[0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.

  0.58274002 0.75912519 0.92823562]]


Random permutation matrix:
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


Mixed matrix
[[0.98436037 0.         0.         0.69893929 0.         0.
  0.         0.         0.40404036 0.         0.         0.69204136
  0.51533375 0.         0.        ]
 [0.         0.89835608 0.        

 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Mixed matrix
[[0.84271318 0.         0.         0.         0.7143981  0.
  0.         0.         0.         0.         0.         0.
  0.63661385 0.         0.48372411]
 [0.         0.99362392 0.63743869 0.42370705 0.         0.
  0.         0.         0.         0.72566969 0.67218507 0.
  0.         0.         0.        ]
 [0.         0.63743869 0.90072627 0.78293672 0.         0.
  0.         0.         0.         0.73637742 0.42615929 0.
  0.         0.         0.        ]
 [0.         0.42370705 0.78293672 0.87883702 0.         0.
  0.         0.         0.         0.56131656 0.2010911  0.
  0.         0.         0.        ]
 [0.7143981  0.         0.         0.         0.88208202 0.
  0.         0.         0.         0.         0.         0.
  0.52767803 0.         0.71942292]
 [0.         0.         0.         0.         0.         0.89927396
  0.         0.54574774 0.         0.         0.         0.
  0.         0.4638594  0.  

Given random block matrix:
[[0.80238042 0.51547016 0.35744055 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.51547016 0.76284081 0.50457259 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.35744055 0.50457259 0.93980681 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.94099165 0.67631518 0.46303861
  0.25507088 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.67631518 0.99070291 0.73856761
  0.56607562 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.        

Random permutation matrix:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0.

 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Mixed matrix
[[0.84787545 0.         0.         0.         0.         0.80361055
  0.         0.35777659 0.         0.         0.55507847 0.
  0.         0.         0.         0.         0.         0.17226543
  0.         0.         0.        ]
 [0.         0.97959335 0.         0.73313967 0.         0.
  0.         0.         0.         0.         0.         0.74346671
  0.         0.         0.         0.63157557 0.55650941 0.
  0.         0.         0.        ]
 [0.         0.         0.94816221 0.         0.         0.
  0.21112007 0.         0.63676346 0.         0.         0.
  0.37738832 0.         0.49689101 0.         0.         0.
  0.         0.83425822 0.        ]
 [0.         0.73313967 0.         0.88105019 0.         0.
  0.         0.         0.         0.         0.         0.54194023
  0.         0.         0.         0.35535202 0.8274364  0.
  0.         0.         0.        ]
 [0.         0.       

 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Mixed matrix
[[0.9319499  0.65835609 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.40712001]
 [0.65835609 0.97519728 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.58663467]
 [0.         0.         0.94526986 0.79638488 0.65481292 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.5899202  0.        ]
 [0.         0.         0.79638488 0.8180576  0.58197609 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.72528018 0.        ]
 [0.         0.         0.65481292 0.58197609 0.89683374 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.227

Given random block matrix:
[[0.9117568  0.61809757 0.3861719  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.61809757 0.95658035 0.54015977 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.3861719  0.54015977 0.98991727 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.97721466 0.69686386 0.46674986
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.69686386 0.80282222 0.5411359
  0.         0.         0.         0.         0.         0.
  0.         0.   

Given random block matrix:
[[0.856821   0.53585385 0.36301682 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.53585385 0.88425681 0.53198103 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.36301682 0.53198103 0.84793302 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.98476178 0.74677305 0.44159178
  0.26224738 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.74677305 0.97173522 0.73430168
  0.5428411  0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
 

  0.35845693 0.54428835 0.71339108 0.78317052 0.86239896]]


Random permutation matrix:
[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

[[0.8466725  0.54001837 0.41125067 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.54001837 0.78719675 0.55187096 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.41125067 0.55187096 0.94990523 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.90919749 0.81851359 0.62993905
  0.45874666 0.32948433 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.  

[[0.95841786 0.7954997  0.51534702 0.26396976 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.7954997  0.8056215  0.74030519 0.50198965 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.51534702 0.74030519 0.85667959 0.6363561  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.26396976 0.50198965 0.6363561  0.97355204 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.82526583 0.75447225
  0.4496395  0.34629714 

[[0.97185391 0.62487414 0.5631781  0.2984435  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.62487414 0.83869512 0.65003411 0.4621723  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.5631781  0.65003411 0.93639165 0.76490445 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.2984435  0.4621723  0.76490445 0.85036532 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0

Given random block matrix:
[[0.89370816 0.74177582 0.47918835 0.38162434 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.74177582 0.9686165  0.61895229 0.52927512 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.47918835 0.61895229 0.95929125 0.69985887 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.38162434 0.52927512 0.69985887 0.84279036 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0.

[[0.8936101  0.         0.         0.46630668 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.26249464 0.         0.         0.76612897 0.
  0.         0.         0.         0.         0.         0.67165247
  0.         0.         0.         0.41136469 0.         0.        ]
 [0.         0.90835759 0.         0.         0.         0.8420494
  0.64949865 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.6124152  0.         0.47522838 0.
  0.         0.         0.7251542  0.         0.         0.        ]
 [0.         0.         0.85773436 0.         0.         0.
  0.         0.         0.75249606 0.         0.         0.84598666
  0.47796861 0.         0.         0.         0.         0.69462812
  0.         0.58122071 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.46630668 0.         0.         0.95657

  0.         0.         0.         0.90218885]]


Given random block matrix:
[[0.76262956 0.54866961 0.30524137 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.54866961 0.91854767 0.63088802 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.30524137 0.63088802 0.80448531 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.92137889 0.70842008 0.44908418
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.   

[[0.98899504 0.         0.49989699 0.         0.         0.
  0.76058544 0.         0.         0.         0.         0.
  0.         0.         0.         0.62566262 0.         0.
  0.75624082 0.         0.         0.         0.        ]
 [0.         0.8143656  0.         0.77799369 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.71055576 0.         0.         0.55780433
  0.         0.         0.         0.         0.        ]
 [0.49989699 0.         0.9929971  0.         0.         0.
  0.51756774 0.         0.         0.         0.         0.
  0.         0.         0.         0.70740293 0.         0.
  0.16686591 0.         0.         0.         0.        ]
 [0.         0.77799369 0.         0.82984482 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.45877963 0.         0.         0.71069018
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.      

[[0.86799062 0.66556923 0.46379935 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.66556923 0.89054444 0.57270814 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.46379935 0.57270814 0.90837265 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.        ]
 [0.         0.         0.         0.92515453 0.50063803 0.34919148
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.       

Given random block matrix:
[[0.86596748 0.57740819 0.42860673 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.57740819 0.94307109 0.6128251  0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.42860673 0.6128251  0.85925057 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.84565192 0.60397837 0.36710192
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.  

[[0.92555783 0.         0.22387199 0.         0.76242329 0.
  0.         0.         0.         0.         0.         0.
  0.69312763 0.55044889 0.         0.         0.37386088 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.93794504 0.         0.63677757 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.69449475 0.         0.         0.
  0.85160329 0.81290894 0.         0.5600555  0.         0.
  0.         0.         0.         0.        ]
 [0.22387199 0.         0.98077632 0.         0.38302775 0.
  0.         0.         0.         0.         0.         0.
  0.5163241  0.66382166 0.         0.         0.74829004 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.63677757 0.         0.98986445 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    

[[0.80373005 0.51713363 0.35246222 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.51713363 0.9715528  0.69744342 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.35246222 0.69744342 0.86818473 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.75280832 0.55564428 0.49361675
  0. 

[[0.86386919 0.         0.         0.         0.         0.
  0.60774999 0.         0.         0.         0.         0.
  0.21267543 0.         0.         0.45967009 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.90598309 0.         0.         0.3197974  0.
  0.         0.         0.         0.         0.         0.59718028
  0.         0.         0.         0.         0.         0.
  0.78627217 0.         0.         0.         0.         0.
  0.81592598 0.47543339]
 [0.         0.         0.86742829 0.75777477 0.         0.
  0.         0.         0.         0.         0.38840411 0.
  0.         0.69431881 0.         0.         0.         0.
  0.         0.         0.         0.         0.51196786 0.
  0.         0.        ]
 [0.         0.         0.75777477 0.92708864 0.         0.
  0.         0.         0.         0.         0.27419546 0.
  0.         0.56246235 0.         0.         0.         0.
  0.         0.  

Given random block matrix:
[[0.78326591 0.64615552 0.33898386 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.64615552 0.89886351 0.70387126 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.33898386 0.70387126 0.96840299 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.82532789 0.6959538  0.52425109
  0.2310961

[[0.89712625 0.72761701 0.41020527 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.72761701 0.9155635  0.71765477 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.41020527 0.71765477 0.91402304 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.96407649 0.77754269 0

[[0.99627773 0.         0.         0.         0.2885074  0.
  0.79551912 0.         0.76005003 0.         0.         0.
  0.70013551 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.50574502 0.         0.        ]
 [0.         0.84531998 0.         0.         0.         0.
  0.         0.17316832 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.59310315 0.         0.         0.         0.
  0.46182578 0.82386414 0.         0.         0.         0.        ]
 [0.         0.         0.89397671 0.         0.         0.
  0.         0.         0.         0.         0.         0.2735583
  0.         0.4447896  0.         0.         0.7367789  0.64532613
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.82300113 0.         0

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
  0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0.

[[0.93938237 0.         0.54160753 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.61697782 0.         0.36617975 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.99538702 0.         0.         0.63320177 0.
  0.         0.         0.         0.         0.53817997 0.
  0.         0.         0.         0.         0.         0.
  0.62652698 0.         0.80334716 0.         0.         0.
  0.         0.         0.         0.76763936 0.        ]
 [0.54160753 0.         0.94318861 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.70031671 0.         0.71437026 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.9546242  0.         0.67453128
  0.         0.         0.         0.6

[[0.90872457 0.77294268 0.40492024 0.38742587 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.77294268 0.85331808 0.63448377 0.50758465 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.40492024 0.63448377 0.91992947 0.68058904 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.38742587 0.50758465 0.68058904 0.95525403 0.         0

[[0.84741359 0.6802932  0.4471016  0.21153612 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.6802932  0.8467705  0.72004972 0.41508552 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.4471016  0.72004972 0.99439499 0.68944582 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.21153612 0.41508552 0.68944582 0.87244229 0.         0

[[0.92133187 0.         0.70376874 0.         0.         0.
  0.         0.57403388 0.         0.         0.         0.
  0.         0.         0.74595479 0.         0.         0.
  0.         0.         0.         0.         0.40552794 0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.87199029 0.         0.7547522  0.         0.
  0.         0.         0.         0.42805731 0.         0.
  0.         0.         0.         0.         0.         0.21485691
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.57091584 0.         0.
  0.        ]
 [0.70376874 0.         0.94116952 0.         0.         0.
  0.         0.78752524 0.         0.         0.         0.
  0.         0.         0.50061567 0.         0.         0.
  0.         0.         0.         0.         0.53525979 0.
  0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.7547522  0.         0.97084105 0.  

In [31]:
exact_sol_vec = np.genfromtxt("/home/koritskiy/Desktop/exact_sol_vec.csv", delimiter=",")
exact_sol_mat = np.reshape(exact_sol_vec, (25, 25))
mix_permutation_mat = exact_sol_mat.T
np.savetxt("/home/koritskiy/rqc/markowitz_partitioning/data/test_matrices/55555/mix_permutation_mat55555.csv", mix_permutation_mat, delimiter=",")