In [1]:
import numpy as np
import time
import os
os.chdir('/home/koritskiy/Yandex.Disk/personal/rqc/markowitz_partitioning')
os.getcwd()
from modules.partitioning import Partitioning

In [2]:
# np.random.seed(4)
# Make console print look better
np.set_printoptions(precision=2,  # Digits after point
                    linewidth=170,  # Length of the line
                    suppress=True)  # Always fixed point notation (not scientific)

block_dim = 55555
size = 25

In [5]:
# block_mat = Partitioning.rand_sym_block_gen(block_dim, order = True)
# (_, mixed_mat, mix_permutation_mat) = Partitioning.mixed_matrix_generator(block_mat=block_mat)
def path(name) : return "/home/koritskiy/Yandex.Disk/personal/rqc/markowitz_partitioning/data/test_matrices/" + str(block_dim) + "/"+ str(name) + str(block_dim) + ".csv"
block_mat = np.genfromtxt(path("block_mat"), delimiter = ",")
mix_permutation_mat = np.genfromtxt(path("mix_permutation_mat"), delimiter = ",")
mixed_mat = np.genfromtxt(path("mixed_mat"), delimiter = ",")
part = Partitioning(mixed_mat, theta = 500)

# block_mat - matrix with block structure of block_dim
# mixed_mat - block_mat that was permuted
# mix_permutation_mat - permutation mat that was applied to block_mat


In [ ]:
# # 1. Перемножить матрицы и получить блочную
# # 2. Проверить энергии

# #1
# exact_perm = mix_permutation_mat.T
# np.dot (exact_perm.T, np.dot(mixed_mat, exact_perm))

# #2
# exact_sol = np.reshape(exact_perm.T, (1, size ** 2))[0]
# en1 = part.solution_energy(exact_sol)
# en2 = np.dot(exact_sol, np.dot(part.qubo_mat,exact_sol))
# print(en1)
# print(en2)

In [6]:
%load_ext jupyternotify

<IPython.core.display.Javascript object>

In [7]:
%%notify

start = time.time()
_, solution = part.kerberos_solver(max_subproblem_size = 60)
end = time.time()
print(f"Sultuion time is {end - start}")

Sultuion time is 80.87163758277893


<IPython.core.display.Javascript object>

In [16]:
part.solution_energy(solution)

-24766.72647044957

In [15]:

part.solution_energy(np.reshape(mix_permutation_mat,(1,625))[0])

-24776.287201989973

In [10]:
part.permutation_mat = part.list_to_mat(solution)
print("Solution permutation matrix:")
print(part.permutation_mat)
print("\n")

# Check, whether solution matrix is permutation one
if not part.permutation_check(part.permutation_mat):
    print('\033[93m' + "Solution is not permutation matrix. "
          "Trying to fix it" + '\033[0m')
    new_solution_permutation_mat = part.to_permutation(part.permutation_mat)
    if part.permutation_check(new_solution_permutation_mat):
        print('\033[93m' + "Success!" + '\033[0m')
        part.permutation_mat = new_solution_permutation_mat
    print("Solution matrix after fixing:")
    print(part.permutation_mat)

part.ordered_mat = part.permute(part.permutation_mat, part.mixed_mat)
print("Ordered matrix:")
print(part.ordered_mat)
print("\n")


Solution permutation matrix:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0

In [46]:
# Exact solution

mixed_mat = np.genfromtxt("/home/koritskiy/markowitz_partitioning/data/test_matrices/55555/mixed_mat55555.csv", delimiter = ",")

part = Partitioning(mixed_mat, theta = 50)
# exact_sol_mat = mix_permutation_mat.T
# exact_sol_vec = np.reshape(exact_sol_mat.T, (1, size ** 2))[0]
exact_sol_vec_file = np.genfromtxt("/home/koritskiy/markowitz_partitioning/data/test_matrices/55555/exact_sol_vec55555.csv", delimiter = ",")
part.solution_energy(exact_sol_vec_file)
boev_vec = [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
boev_mat = np.array(boev_vec).reshape((25,25))
part.solution_energy(boev_vec)
print(np.dot(boev_mat.T, np.dot(mixed_mat, boev_mat)))

[[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.93 0.93 0.33 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.93 0.93 0.33 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.33 0.33 0.85 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.

In [30]:
# exact_sol_mat_file = np.genfromtxt("/home/koritskiy/Downloads/telegram/exact_solution_35.csv", delimiter = ",")
exact_sol_vec_file = np.genfromtxt("/home/koritskiy/snap/skype/common/exact_sol_vec55555.csv", delimiter = ",")
qubo_mat_file = np.genfromtxt("/home/koritskiy/snap/skype/common/part_qubo_mat55555.csv", delimiter = ",")
np.dot(exact_sol_vec_file.T, np.dot(qubo_mat_file, exact_sol_vec_file))

OSError: /home/koritskiy/snap/skype/common/exact_sol_vec55555.csv not found.

In [ ]:
path = "/home/koritskiy/Yandex.Disk/Personal/RQC/Markowitz_partitioning/data/" + str(block_dim)
if not os.path.exists(path):
    os.makedirs(path)
np.savetxt(path + "/part_qubo_mat" + str(block_dim) + ".csv" , part.qubo_mat, delimiter=",")
np.savetxt(path + "/exact_sol_vec" + str(block_dim) + ".csv", exact_sol_vec, delimiter=",")
np.savetxt(path + "/kerberos_sol_vec" + str(block_dim) + ".csv", solution, delimiter=",")
np.savetxt(path + "/block_mat" + str(block_dim) + ".csv", block_mat, delimiter=",")
np.savetxt(path + "/mixed_mat" + str(block_dim) + ".csv", mixed_mat, delimiter=",")

In [ ]:
mat = np.array([1,3,4])
mat.__name__